### ISSUE TITLE
Cannot set menu icon

### ISSUE THREAD

**Issue by mfat** [neeeeow/Bluecurve#8]
Hi thanks for the amazing work. Can't tell how excited i am to have this theme.
I ran this command on Debian 12
`gsettings set org.mate.panel.menubar icon-name 'redhat-icon-panel-menu'`
But the menu icon didn't change. A logout didn't work either.

**Comment by mfat** [comment]
Actually the icon appears in classic application menu but not in the brisk menu and compact menu.

**Comment by neeeeow** [comment]
This is expected behaviour. The icon of brisk-menu can be changed by right clicking on the icon and going in to preferences.

The compact menu icon can be changed by going in to dconf-editor and changing the icon of the compact menu (the object ID of the compact menu isn't always the same and thus it can't be changed easily through the command line).

**Comment by vyvir** [comment]
> Hi thanks for the amazing work. Can't tell how excited i am to have this theme. I ran this command on Debian 12 `gsettings set org.mate.panel.menubar icon-name 'redhat-icon-panel-menu'` But the menu icon didn't change. A logout didn't work either.

This is unimplemented behavior for all but classic menu.
There is a Brisk Menu fork you could manually compile (https://github.com/Ionic/brisk-menu/tree/feature/customizable-icon) or download and install the patched version on OpenSUSE (https://build.opensuse.org/package/show/home:asdhio/brisk-menu).
